<?php

function calcPercentChange($stat, $prevStat) {
  if($stat->count === 0 && $prevStat->count === 0) return 0;
  if($prevStat->count === 0) return 100;
  return round((($stat->count - $prevStat->count) / ($prevStat->count)) * 100);
}

function randomElement($array) {
  return $array[mt_rand(0, count($array) - 1)];
}

function formatNumber($number) {
    // Если число меньше 1000, возвращаем как есть
    if ($number < 1000) {
        return $number;
    }
    
    // Миллиарды
    if ($number >= 1000000000) {
        $result = $number / 1000000000;
        $formatted = number_format($result, 2, '.', '');
        // Убираем лишние нули
        $formatted = rtrim(rtrim($formatted, '0'), '.');
        return $formatted . ' млрд';
    }
    
    // Миллионы
    if ($number >= 1000000) {
        $result = $number / 1000000;
        $formatted = number_format($result, 2, '.', '');
        // Убираем лишние нули
        $formatted = rtrim(rtrim($formatted, '0'), '.');
        return $formatted . ' млн';
    }
    
    // Тысячи
    if ($number >= 1000) {
        $result = $number / 1000;
        $formatted = number_format($result, 2, '.', '');
        // Убираем лишние нули
        $formatted = rtrim(rtrim($formatted, '0'), '.');
        return $formatted . ' тыс';
    }
    
    return $number;
}

function ruMonth($timestamp) {
  $month = array(
    1  => 'янв',
    2  => 'фев',
    3  => 'март',
    4  => 'апр',
    5  => 'май', 
    6  => 'июн',
    7  => 'июл',
    8  => 'авг',
    9  => 'сен',
    10 => 'окт',
    11 => 'ноя',
    12 => 'дек'
  );
  return $month[date('n', $timestamp)];

  //echo date('Y', $timestamp).'-'.$month[date('n', $timestamp)].'-'.date('d', $timestamp);
}
function ruMonthFull($timestamp) {
  $month = array(
    1  => 'января',
    2  => 'февраля',
    3  => 'марта',
    4  => 'апреля',
    5  => 'мая', 
    6  => 'июня',
    7  => 'июля',
    8  => 'августа',
    9  => 'сентября',
    10 => 'октября',
    11 => 'ноября',
    12 => 'декабря'
  );
  return $month[date('n', $timestamp)];
}
function ruMonthFull2($timestamp) {
  $month = array(
    1  => 'январь',
    2  => 'февраль',
    3  => 'март',
    4  => 'апрель',
    5  => 'май', 
    6  => 'июнь',
    7  => 'июль',
    8  => 'август',
    9  => 'сентябрь',
    10 => 'октябрь',
    11 => 'ноябрь',
    12 => 'декабрь'
  );
  return $month[date('n', $timestamp)];
}

function resolveSwitchValue($item, $field) {
  if($item) return $item[$field['key']] == true;
  if($field && isset($field['value'])) return $field['value'];
  return false;
}

function searchForType($id, $array) {
  foreach ($array as $key => $val) {
      if ($val['type'] === $id) {
          return $key;
      }
  }
  return null;
}

/*function markdown_escape($text) {
  return str_replace([
    '\\', '-', '#', '*', '+', '`', '.', '[', ']', '(', ')', '!', '&', '<', '>', '_', '{', '}', '|', '='], [
    '\\\\', '\-', '\#', '\*', '\+', '\`', '\.', '\[', '\]', '\(', '\)', '\!', '\&', '\<', '\>', '\_', '\{', '\}', '\|', '\='
  ], $text);
}*/

function markdown_escape($text) {
  $text = str_replace(['.', '+', '-', /*'(', ')',*/ '!', '='], ['\.', '\+', '\-', /*'\(', '\)',*/ '\!', '\='], $text);
  // экранируем скобки только если есть мэтч по пробелу
  if(preg_match("# \(([^)]*)\)#", $text)) {
    $text = preg_replace("# \(([^)]*)\)#", " \($1\)", $text);
  }
  return $text;
}

function translit($text) {
  //$text = preg_replace("/\s|&nbsp;/",'',$text);
  $text = htmlentities($text, null, 'utf-8');
  $text = str_replace("&nbsp;", "-", $text);
  $text = str_replace("\u{200B}", "", $text);
  $text = str_replace("\u{FEFF}", "", $text);
  $text = str_replace("\u{2060}", "", $text);
  $text = str_replace("\n", "", $text);
  $text = html_entity_decode($text);

  $cyr = [
    /*'Љ', 'Њ', 'Џ', 'џ', 'ш', 'ђ', 'ч', 'ћ', 'ж', 'љ', 'њ', 'Ш', 'Ђ', 'Ч', 'Ћ', 'Ж','Ц','ц',*/
    'а','б','в','г','д','е','ё','ж','з','и','й','к','л','м','н','о','п', 'р','с','т','у','ф','х','ц','ч','ш','щ','ъ','ы','ь','э','ю','я', 'А','Б','В','Г','Д','Е','Ё','Ж','З','И','Й','К','Л','М','Н','О','П', 'Р','С','Т','У','Ф','Х','Ц','Ч','Ш','Щ','Ъ','Ы','Ь','Э','Ю','Я',
   ' ', ':', '—', ',', '?', '!', '(', ')', '"', '\'', '«', '»', '’', '.', '+', '*', '№', '½', '&', '+', '/', '–', '°', '`', '=', '։', '.', '+', 'о́', '⇄', 'ө', 'ә', '‑',
    'ë', 'о́', 'á', 'ѣ', 'ғ', 'é', 'á', '―', '×', '…', 'Š', 'ö', 'й', 'й'
  ];
  $lat = [
    /*'Lj', 'Nj', 'Dž', 'dž', 'š', 'đ', 'č', 'ć', 'ž', 'lj', 'nj', 'Š', 'Đ', 'Č', 'Ć', 'Ž','C','c',*/ 
    'a','b','v','g','d','e','io','zh','z','i','y','k','l','m','n','o','p', 'r','s','t','u','f','h','ts','ch','sh','sht','a','i','y','e','yu','ya', 'A','B','V','G','D','E','Io','Zh','Z','I','Y','K','L','M','N','O','P', 'R','S','T','U','F','H','Ts','Ch','Sh','Sht','A','I','Y','e','Yu','Ya',
   '-', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '-', '-', '', '', '', '', '', '', 'o', '', 'o', 'e', '-',
    'e', 'o', 'a', 'e', 'g', 'e', 'a', '-', 'x', '', 's', 'o', 'i', 'i'
  ];

  $text = trim(str_replace($cyr, $lat, $text));
  $text = preg_replace("/-{2,}/", '-', $text);
  $text = preg_replace("/^-/", '', $text);

  return $text;
}

function is_bot($userAgent){
  $bots = array(
      'Googlebot'
      , 'Baiduspider'
      , 'ia_archiver'
      , 'R6_FeedFetcher'
      , 'NetcraftSurveyAgent'
      , 'Sogou web spider'
      , 'bingbot'
      , 'Yahoo! Slurp'
      , 'facebookexternalhit'
      , 'PrintfulBot'
      , 'msnbot'
      , 'Twitterbot'
      , 'UnwindFetchor'
      , 'urlresolver'
      , 'Butterfly'
      , 'TweetmemeBot'
      , 'PaperLiBot'
      , 'MJ12bot'
      , 'AhrefsBot'
      , 'Exabot'
      , 'Ezooms'
      , 'YandexBot'
      , 'SearchmetricsBot'
      , 'picsearch'
      , 'TweetedTimes Bot'
      , 'QuerySeekerSpider'
      , 'ShowyouBot'
      , 'woriobot'
      , 'merlinkbot'
      , 'BazQuxBot'
      , 'Kraken'
      , 'SISTRIX Crawler'
      , 'R6_CommentReader'
      , 'magpie-crawler'
      , 'GrapeshotCrawler'
      , 'PercolateCrawler'
      , 'MaxPointCrawler'
      , 'NetSeer crawler'
      , 'grokkit-crawler'
      , 'SMXCrawler'
      , 'PulseCrawler'
      , 'Y!J-BRW'
      , '80legs'
      , 'Mediapartners-Google'
      , 'InAGist'
      , 'Python-urllib'
      , 'NING'
      , 'TencentTraveler'
      , 'Feedfetcher-Google'
      , 'mon.itor.us'
      , 'spbot'
      , 'Feedly'
      , 'bitlybot'
      , 'ADmantX'
      , 'Niki-Bot'
      , 'Pinterest'
      , 'python-requests'
      , 'DotBot'
      , 'HTTP_Request2'
      , 'linkdexbot'
      , 'A6-Indexer'
      , 'TwitterFeed'
      , 'Microsoft Office'
      , 'Pingdom'
      , 'BTWebClient'
      , 'KatBot'
      , 'SiteCheck'
      , 'proximic'
      , 'Sleuth'
      , 'Abonti'
      , '(BOT for JCE)'
      , 'Tiny Tiny RSS'
      , 'newsblur'
      , 'updown_tester'
      , 'linkdex'
      , 'baidu'
      , 'searchmetrics'
      , 'genieo'
      , 'majestic12'
      , 'spinn3r'
      , 'profound'
      , 'domainappender'
      , 'VegeBot'
      , 'terrykyleseoagency.com'
      , 'CommonCrawler Node'
      , 'AdlesseBot'
      , 'libwww-perl'
      , 'rogerbot-crawler'
      , 'ltx71'
      , 'Qwantify'
      , 'Traackr.com'
      , 'Re-Animator Bot'
      , 'Pcore-HTTP'
      , 'BoardReader'
      , 'omgili'
      , 'okhttp'
      , 'CCBot'
      , 'Java/1.8'
      , 'semrush.com'
      , 'feedbot'
      , 'CommonCrawler'
      , 'ibwww-perl'
      , 'rogerbot'
      , 'MegaIndex'
      , 'BLEXBot'
      , 'FlipboardProxy'
      , 'techinfo@ubermetrics-technologies.com'
      , 'trendictionbot'
      , 'Mediatoolkitbot'
      , 'trendiction'
      , 'ubermetrics'
      , 'ScooperBot'
      , 'TrendsmapResolver'
      , 'Nuzzel'
      , 'Go-http-client'
      , 'Applebot'
      , 'LivelapBot'
      , 'GroupHigh'
      , 'SemrushBot'
      , 'commoncrawl'
      , 'istellabot'
      , 'DomainCrawler'
      , 'cs.daum.net'
      , 'StormCrawler'
      , 'GarlikCrawler'
      , 'The Knowledge AI'
      , 'getstream.io/winds'
      , 'YisouSpider'
      , 'archive.org_bot'
      , 'semantic-visions.com'
      , 'FemtosearchBot'
      , '360Spider'
      , 'linkfluence.com'
      , 'glutenfreepleasure.com'
      , 'Gluten Free Crawler'
      , 'YaK/1.0'
      , 'Cliqzbot'
      , 'app.hypefactors.com'
      , 'axios'
      , 'webdatastats.com'
      , 'schmorp.de'
      , 'SEOkicks'
      , 'DuckDuckBot'
      , 'Barkrowler'
      , 'ZoominfoBot'
      , 'Linguee Bot'
      , 'Mail.RU_Bot'
      , 'OnalyticaBot'
      , 'admantx-adform'
      , 'Zombiebot'
      , 'Nutch'
      , 'SemanticScholarBot'
      , 'Jetslide'
      , 'scalaj-http'
      , 'XoviBot'
      , 'sysomos.com'
      , 'PocketParser'
      , 'newspaper'
      , 'serpstatbot'
      , 'MetaJobBot'
      , 'SeznamBot/3.2'
      , 'VelenPublicWebCrawler/1.0'
      , 'WordPress.com mShots'
      , 'adscanner'
      , 'BacklinkCrawler'
      , 'netEstate NE Crawler'
      , 'Astute SRM'
      , 'GigablastOpenSource/1.0'
      , 'DomainStatsBot'
      , 'Winds: Open Source RSS & Podcast'
      , 'dlvr.it'
      , 'BehloolBot'
      , '7Siters'
      , 'AwarioSmartBot'
      , 'Apache-HttpClient/5'
      , 'Seekport Crawler'
      , 'AHC/2.1'
      , 'eCairn-Grabber'
      , 'mediawords bot'
      , 'PHP-Curl-Class'
      , 'Scrapy'
      , 'curl/7'
      , 'Blackboard'
      , 'NetNewsWire'
      , 'node-fetch'
      , 'admantx'
      , 'metadataparser'
      , 'Domains Project'
      , 'SerendeputyBot'
      , 'Moreover'
      , 'DuckDuckGo' 
      , 'monitoring-plugins'
      , 'Selfoss'
      , 'Adsbot'
      , 'acebookexternalhit'
      , 'SpiderLing'
      , 'Cocolyzebot'
      , 'TTD-Content'
      , 'superfeedr'
      , 'Twingly'
      , 'Google-Apps-Scrip'
      , 'LinkpadBot'
      , 'CensysInspect'
      , 'Reeder'
      , 'tweetedtimes'
      , 'Amazonbot'
      , 'MauiBot'
      , 'Symfony BrowserKit'
      , 'DataForSeoBot'
      , 'GoogleProducer'
      , 'TinEye-bot-live'
      , 'sindresorhus/got'
      , 'CriteoBot'
      , 'Down/5'
      , 'Yahoo Ad monitoring'
      , 'MetaInspector'
      , 'PetalBot'
      , 'MetadataScraper'
      , 'Cloudflare SpeedTest'
      , 'aiohttp'
      , 'AppEngine-Google'
      , 'heritrix'
      , 'sqlmap'
      , 'Buck'
      , 'wp_is_mobile'
      , '01h4x.com'
      , '404checker'
      , '404enemy'
      , 'AIBOT'
      , 'ALittle Client'
      , 'ASPSeek'
      , 'Aboundex'
      , 'Acunetix'
      , 'AfD-Verbotsverfahren'
      , 'AiHitBot'
      , 'Aipbot'
      , 'Alexibot'
      , 'AllSubmitter'
      , 'Alligator'
      , 'AlphaBot'
      , 'Anarchie'
      , 'Anarchy'
      , 'Anarchy99'
      , 'Ankit'
      , 'Anthill'
      , 'Apexoo'
      , 'Aspiegel'
      , 'Asterias'
      , 'Atomseobot'
      , 'Attach'
      , 'AwarioRssBot'
      , 'BBBike'
      , 'BDCbot'
      , 'BDFetch'
      , 'BackDoorBot'
      , 'BackStreet'
      , 'BackWeb'
      , 'Backlink-Ceck'
      , 'Badass'
      , 'Bandit'
      , 'BatchFTP'
      , 'Battleztar Bazinga'
      , 'BetaBot'
      , 'Bigfoot'
      , 'Bitacle'
      , 'BlackWidow'
      , 'Black Hole'
      , 'Blow'
      , 'BlowFish'
      , 'Boardreader'
      , 'Bolt'
      , 'BotALot'
      , 'Brandprotect'
      , 'Brandwatch'
      , 'Buddy'
      , 'BuiltBotTough'
      , 'BuiltWith'
      , 'Bullseye'
      , 'BunnySlippers'
      , 'BuzzSumo'
      , 'CATExplorador'
      , 'CODE87'
      , 'CSHttp'
      , 'Calculon'
      , 'CazoodleBot'
      , 'Cegbfeieh'
      , 'CheTeam'
      , 'CheeseBot'
      , 'CherryPicker'
      , 'ChinaClaw'
      , 'Chlooe'
      , 'Citoid'
      , 'Claritybot'
      , 'Cloud mapping'
      , 'Cogentbot'
      , 'Collector'
      , 'Copier'
      , 'CopyRightCheck'
      , 'Copyscape'
      , 'Cosmos'
      , 'Craftbot'
      , 'Crawling at Home Project'
      , 'CrazyWebCrawler'
      , 'Crescent'
      , 'CrunchBot'
      , 'Curious'
      , 'Custo'
      , 'CyotekWebCopy'
      , 'DBLBot'
      , 'DIIbot'
      , 'DSearch'
      , 'DTS Agent'
      , 'DataCha0s'
      , 'DatabaseDriverMysqli'
      , 'Demon'
      , 'Deusu'
      , 'Devil'
      , 'Digincore'
      , 'DigitalPebble'
      , 'Dirbuster'
      , 'Disco'
      , 'Discobot'
      , 'Discoverybot'
      , 'Dispatch'
      , 'DittoSpyder'
      , 'DnBCrawler-Analytics'
      , 'DnyzBot'
      , 'DomCopBot'
      , 'DomainAppender'
      , 'DomainSigmaCrawler'
      , 'Dotbot'
      , 'Download Wonder'
      , 'Dragonfly'
      , 'Drip'
      , 'ECCP/1.0'
      , 'EMail Siphon'
      , 'EMail Wolf'
      , 'EasyDL'
      , 'Ebingbong'
      , 'Ecxi'
      , 'EirGrabber'
      , 'EroCrawler'
      , 'Evil'
      , 'Express WebPictures'
      , 'ExtLinksBot'
      , 'Extractor'
      , 'ExtractorPro'
      , 'Extreme Picture Finder'
      , 'EyeNetIE'
      , 'FDM'
      , 'FHscan'
      , 'Fimap'
      , 'Firefox/7.0'
      , 'FlashGet'
      , 'Flunky'
      , 'Foobot'
      , 'Freeuploader'
      , 'FrontPage'
      , 'Fuzz'
      , 'FyberSpider'
      , 'Fyrebot'
      , 'G-i-g-a-b-o-t'
      , 'GT::WWW'
      , 'GalaxyBot'
      , 'Genieo'
      , 'GermCrawler'
      , 'GetRight'
      , 'GetWeb'
      , 'Getintent'
      , 'Gigabot'
      , 'Go!Zilla'
      , 'Go-Ahead-Got-It'
      , 'GoZilla'
      , 'Gotit'
      , 'GrabNet'
      , 'Grabber'
      , 'Grafula'
      , 'GrapeFX'
      , 'GridBot'
      , 'HEADMasterSEO'
      , 'HMView'
      , 'HTMLparser'
      , 'HTTP::Lite'
      , 'HTTrack'
      , 'Haansoft'
      , 'HaosouSpider'
      , 'Harvest'
      , 'Havij'
      , 'Hloader'
      , 'HonoluluBot'
      , 'Humanlinks'
      , 'HybridBot'
      , 'IDBTE4M'
      , 'IDBot'
      , 'IRLbot'
      , 'Iblog'
      , 'Id-search'
      , 'IlseBot'
      , 'Image Fetch'
      , 'Image Sucker'
      , 'IndeedBot'
      , 'Indy Library'
      , 'InfoNaviRobot'
      , 'InfoTekies'
      , 'Intelliseek'
      , 'InterGET'
      , 'InternetSeer'
      , 'Internet Ninja'
      , 'Iria'
      , 'Iskanie'
      , 'IstellaBot'
      , 'JOC Web Spider'
      , 'JamesBOT'
      , 'Jbrofuzz'
      , 'JennyBot'
      , 'JetCar'
      , 'Jetty'
      , 'JikeSpider'
      , 'Joomla'
      , 'Jorgee'
      , 'JustView'
      , 'Jyxobot'
      , 'Kenjin Spider'
      , 'Keybot Translation-Search-Machine'
      , 'Keyword Density'
      , 'Kinza'
      , 'Kozmosbot'
      , 'LNSpiderguy'
      , 'LWP::Simple'
      , 'Lanshanbot'
      , 'Larbin'
      , 'Leap'
      , 'LeechFTP'
      , 'LeechGet'
      , 'LexiBot'
      , 'Lftp'
      , 'LibWeb'
      , 'Libwhisker'
      , 'LieBaoFast'
      , 'Lightspeedsystems'
      , 'Likse'
      , 'LinkScan'
      , 'LinkWalker'
      , 'Linkbot'
      , 'LinkextractorPro'
      , 'LinksManager'
      , 'LinqiaMetadataDownloaderBot'
      , 'LinqiaRSSBot'
      , 'LinqiaScrapeBot'
      , 'Lipperhey'
      , 'Lipperhey Spider'
      , 'Litemage_walker'
      , 'Lmspider'
      , 'MFC_Tear_Sample'
      , 'MIDown tool'
      , 'MIIxpc'
      , 'MQQBrowser'
      , 'MSFrontPage'
      , 'MSIECrawler'
      , 'MTRobot'
      , 'Mag-Net'
      , 'Magnet'
      , 'Majestic-SEO'
      , 'Majestic12'
      , 'Majestic SEO'
      , 'MarkMonitor'
      , 'MarkWatch'
      , 'Mass Downloader'
      , 'Masscan'
      , 'Mata Hari'
      , 'Mb2345Browser'
      , 'MeanPath Bot'
      , 'Meanpathbot'
      , 'metauri'
      , 'MicroMessenger'
      , 'Microsoft Data Access'
      , 'Microsoft URL Control'
      , 'Minefield'
      , 'Mister PiX'
      , 'Moblie Safari'
      , 'Mojeek'
      , 'Mojolicious'
      , 'MolokaiBot'
      , 'Morfeus Fucking Scanner'
      , 'Mozlila'
      , 'Mr.4x3'
      , 'Msrabot'
      , 'Musobot'
      , 'NICErsPRO'
      , 'NPbot'
      , 'Name Intelligence'
      , 'Nameprotect'
      , 'Navroad'
      , 'NearSite'
      , 'Needle'
      , 'Nessus'
      , 'NetAnts'
      , 'NetLyzer'
      , 'NetMechanic'
      , 'NetSpider'
      , 'NetZIP'
      , 'Net Vampire'
      , 'Netcraft'
      , 'Nettrack'
      , 'Netvibes'
      , 'NextGenSearchBot'
      , 'Nibbler'
      , 'Niki-bot'
      , 'Nikto'
      , 'NimbleCrawler'
      , 'Nimbostratus'
      , 'Ninja'
      , 'Nmap'
      , 'Nuclei'
      , 'Octopus'
      , 'Offline Explorer'
      , 'Offline Navigator'
      , 'OnCrawl'
      , 'OpenLinkProfiler'
      , 'OpenVAS'
      , 'Openfind'
      , 'Openvas'
      , 'OrangeBot'
      , 'OrangeSpider'
      , 'OutclicksBot'
      , 'OutfoxBot'
      , 'PECL::HTTP'
      , 'PHPCrawl'
      , 'POE-Component-Client-HTTP'
      , 'PageAnalyzer'
      , 'PageGrabber'
      , 'PageScorer'
      , 'PageThing.com'
      , 'Page Analyzer'
      , 'Pandalytics'
      , 'Panscient'
      , 'Papa Foto'
      , 'Pavuk'
      , 'PeoplePal'
      , 'Petalbot'
      , 'Pi-Monster'
      , 'Picscout'
      , 'Picsearch'
      , 'PictureFinder'
      , 'Piepmatz'
      , 'Pimonster'
      , 'Pixray'
      , 'PleaseCrawl'
      , 'Pockey'
      , 'ProPowerBot'
      , 'ProWebWalker'
      , 'Probethenet'
      , 'Psbot'
      , 'Pu_iN'
      , 'Pump'
      , 'PxBroker'
      , 'PyCurl'
      , 'QueryN Metasearch'
      , 'Quick-Crawler'
      , 'RSSingBot'
      , 'RankActive'
      , 'RankActiveLinkBot'
      , 'RankFlex'
      , 'RankingBot'
      , 'RankingBot2'
      , 'Rankivabot'
      , 'RankurBot'
      , 'Re-re'
      , 'ReGet'
      , 'RealDownload'
      , 'Reaper'
      , 'RebelMouse'
      , 'Recorder'
      , 'RedesScrapy'
      , 'RepoMonkey'
      , 'Ripper'
      , 'RocketCrawler'
      , 'Rogerbot'
      , 'SBIder'
      , 'SEOlyticsCrawler'
      , 'SEOprofiler'
      , 'SEOstats'
      , 'SISTRIX'
      , 'SMTBot'
      , 'SalesIntelligent'
      , 'ScanAlert'
      , 'Scanbot'
      , 'ScoutJet'
      , 'Screaming'
      , 'ScreenerBot'
      , 'ScrepyBot'
      , 'Searchestate'
      , 'Seekport'
      , 'SemanticJuice'
      , 'Semrush'
      , 'SentiBot'
      , 'SeoSiteCheckup'
      , 'SeobilityBot'
      , 'Seomoz'
      , 'Shodan'
      , 'Siphon'
      , 'SiteCheckerBotCrawler'
      , 'SiteExplorer'
      , 'SiteLockSpider'
      , 'SiteSnagger'
      , 'SiteSucker'
      , 'Site Sucker'
      , 'Sitebeam'
      , 'Siteimprove'
      , 'Sitevigil'
      , 'SlySearch'
      , 'SmartDownload'
      , 'Snake'
      , 'Snapbot'
      , 'Snoopy'
      , 'SocialRankIOBot'
      , 'Sociscraper'
      , 'Sosospider'
      , 'Sottopop'
      , 'SpaceBison'
      , 'Spammen'
      , 'SpankBot'
      , 'Spanner'
      , 'Spbot'
      , 'SputnikBot'
      , 'Sqlmap'
      , 'Sqlworm'
      , 'Sqworm'
      , 'Steeler'
      , 'Stripper'
      , 'Sucker'
      , 'Sucuri'
      , 'SuperBot'
      , 'SuperHTTP'
      , 'Surfbot'
      , 'SurveyBot'
      , 'Suzuran'
      , 'Swiftbot'
      , 'Szukacz'
      , 'T0PHackTeam'
      , 'T8Abot'
      , 'Teleport'
      , 'TeleportPro'
      , 'Telesoft'
      , 'Telesphoreo'
      , 'Telesphorep'
      , 'TheNomad'
      , 'The Intraformant'
      , 'Thumbor'
      , 'TightTwatBot'
      , 'Titan'
      , 'Toata'
      , 'Toweyabot'
      , 'Tracemyfile'
      , 'Trendiction'
      , 'Trendictionbot'
      , 'True_Robot'
      , 'Turingos'
      , 'Turnitin'
      , 'TurnitinBot'
      , 'TwengaBot'
      , 'Twice'
      , 'Typhoeus'
      , 'URLy.Warning'
      , 'URLy Warning'
      , 'UnisterBot'
      , 'Upflow'
      , 'V-BOT'
      , 'VB Project'
      , 'VCI'
      , 'Vacuum'
      , 'Vagabondo'
      , 'VelenPublicWebCrawler'
      , 'VeriCiteCrawler'
      , 'VidibleScraper'
      , 'Virusdie'
      , 'VoidEYE'
      , 'Voil'
      , 'Voltron'
      , 'WASALive-Bot'
      , 'WBSearchBot'
      , 'WEBDAV'
      , 'WISENutbot'
      , 'WPScan'
      , 'WWW-Collector-E'
      , 'WWW-Mechanize'
      , 'WWW::Mechanize'
      , 'WWWOFFLE'
      , 'Wallpapers'
      , 'Wallpapers/3.0'
      , 'WallpapersHD'
      , 'WeSEE'
      , 'WebAuto'
      , 'WebBandit'
      , 'WebCollage'
      , 'WebCopier'
      , 'WebEnhancer'
      , 'WebFetch'
      , 'WebFuck'
      , 'WebGo IS'
      , 'WebImageCollector'
      , 'WebLeacher'
      , 'WebPix'
      , 'WebReaper'
      , 'WebSauger'
      , 'WebStripper'
      , 'WebSucker'
      , 'WebWhacker'
      , 'WebZIP'
      , 'Web Auto'
      , 'Web Collage'
      , 'Web Enhancer'
      , 'Web Fetch'
      , 'Web Fuck'
      , 'Web Pix'
      , 'Web Sauger'
      , 'Web Sucker'
      , 'Webalta'
      , 'WebmasterWorldForumBot'
      , 'Webshag'
      , 'WebsiteExtractor'
      , 'WebsiteQuester'
      , 'Website Quester'
      , 'Webster'
      , 'Whack'
      , 'Whacker'
      , 'Whatweb'
      , 'Who.is Bot'
      , 'Widow'
      , 'WinHTTrack'
      , 'WiseGuys Robot'
      , 'Wonderbot'
      , 'Woobot'
      , 'Wotbox'
      , 'Wprecon'
      , 'Xaldon WebSpider'
      , 'Xaldon_WebSpider'
      , 'Xenu'
      , 'YoudaoBot'
      , 'Zade'
      , 'Zauba'
      , 'Zermelo'
      , 'Zeus'
      , 'Zitebot'
      , 'ZmEu'
      , 'ZoomBot'
      , 'ZumBot'
      , 'ZyBorg'
      , 'arquivo-web-crawler'
      , 'arquivo.pt'
      , 'autoemailspider'
      , 'backlink-check'
      , 'cah.io.community'
      , 'check1.exe'
      , 'clark-crawler'
      , 'coccocbot'
      , 'cognitiveseo'
      , 'com.plumanalytics'
      , 'crawl.sogou.com'
      , 'crawler.feedback'
      , 'crawler4j'
      , 'dataforseo.com'
      , 'demandbase-bot'
      , 'domainsproject.org'
      , 'eCatch'
      , 'evc-batch'
      , 'facebookscraper'
      , 'gopher'
      , 'instabid'
      , 'internetVista monitor'
      , 'ips-agent'
      , 'isitwp.com'
      , 'iubenda-radar'
      , 'lwp-request'
      , 'lwp-trivial'
      , 'meanpathbot'
      , 'mediawords'
      , 'muhstik-scan'
      , 'oBot'
      , 'page scorer'
      , 'pcBrowser'
      , 'plumanalytics'
      , 'polaris version'
      , 'probe-image-size'
      , 'ripz'
      , 's1z.ru'
      , 'satoristudio.net'
      , 'scan.lol'
      , 'seobility'
      , 'seocompany.store'
      , 'seoscanners'
      , 'seostar'
      , 'sexsearcher'
      , 'sitechecker.pro'
      , 'siteripz'
      , 'sogouspider'
      , 'sp_auditbot'
      , 'spyfu'
      , 'sysscan'
      , 'tAkeOut'
      , 'trendiction.com'
      , 'trendiction.de'
      , 'ubermetrics-technologies.com'
      , 'voyagerx.com'
      , 'webgains-bot'
      , 'webmeup-crawler'
      , 'webpros.com'
      , 'webprosbot'
      , 'x09Mozilla'
      , 'x22Mozilla'
      , 'xpymep1.exe'
      , 'zauba.io'
      , 'zgrab'
      , 'petalsearch'
      , 'protopage'
      , 'Miniflux'
      , 'Feeder'
      , 'Semanticbot' 
      , 'ImageFetcher'
      , 'Mastodon' 
      , 'Neevabot'
      , 'Pleroma'
      , 'Akkoma'
      , 'koyu.space'
      , 'Embedly'
      , 'Mjukisbyxor'
      , 'Giant Rhubarb'
      , 'GozleBot'
      , 'Friendica'
      , 'WhatsApp'
      , 'XenForo'
      , 'Yeti'
      , 'MuckRack'
      , 'PhxBot'
      , 'Bytespider'
      , 'GPTBot'
      , 'SummalyBot'
      , 'LinkedInBot'
      , 'SpiderWeb'
      , 'SpaceCowboys'
      , 'LCC'
      , 'Paqlebot'
      , 'imagesift'
      , 'ows.eu'
      , 'SeznamBot'
      , 'SeznamHomepage'
      , 'ChatGPT'
      , 'Google-Extended'
      , 'GoogleOther'
      , 'anthropic'
      , 'Claude-Web'
      , 'cohere-ai'
      , 'Diffbot'
      , 'FacebookBot'
      , 'ImagesiftBot'
      , 'PerplexityBot'
      , 'Omigili'
      , 'yacybot'
      , 'RepoLookoutBot'
      , 'StractBot'
      , 'IABot'
      , 'rss-is-dead'
      , 'Slackbot'
      , 'Storebot-Google'
      , 'Google-InspectionTool'
      , 'APIs-Google'
      , 'AdsBot-Google'
      , 'Google-Safety'
      , 'WellKnownBot'
      , 'ArchiveBot'
      , 'Sogou'
      , 'iaskspider'
      , 'Qwantbot'
      , 'keys-so-bot'
      , 'ev-crawler'
      , 'OAI-SearchBot'
      , 'InternetMeasurement'
      , 'meta-externalagent'
      );

  foreach($bots as $b)
      {
          if( stripos( $userAgent, $b ) !== false ) return true;
      }
  return false;
}

